fix: update db schema update constraint
graasp/graasp-plugin-recycle-bin pull request #45
Opened 2023-03-15 13:56 UTC by pyphilia

allows rows to update if item moves

close #44

2023-03-16 13:48 UTC, dialexo requested changes
@pyphilia I'm not clear why this change would actually solve the issue

2023-03-16 13:48 UTC, mochiruntime commented on db-schema.sql
> +  "item_id" uuid UNIQUE NOT NULL REFERENCES "item" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
Info: what are the semantics of this change? I'm not I understand the purpose: it should only affect a row in recycled item if the id of the foreign item is affected, e.g. if it changed from UUID x to UUID y. However, this should never happen right? IDs are never re-assigned, even on move right?

2023-03-21 10:15 UTC, pyphilia commented on db-schema.sql
> +  "item_id" uuid UNIQUE NOT NULL REFERENCES "item" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
You're completely right, I've mixed up the line... actually I think we don't use item id anymore but well...

2023-03-22 13:57 UTC, mochiruntime approved these changes
LGTM :cactus:

2023-03-29 09:12 UTC, merged